[profile.default]
src = "src"
out = "out"

optimizer = true
optimizer_runs = 1_000_000
solc_version = "0.8.20"

fs_permissions = [{ access = "read-write", path = "./deployments"}, { access = "read", path = "./"}]

[fmt]
line_length = 120
wrap_comments = true

libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    # 
    # - forge-std
    # - ds-test
    # - solidity-bytes-utilities
    'lib',
    'node_modules',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
